name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # MANDATORY for OIDC / Trusted Publishing
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install

    - name: Build package
      # This creates the dist/ folder with .whl and .tar.gz
      run: uv build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
